# cloudbuild.yaml
steps:
- name: node:16.13.0
  entrypoint: npm
  args: ["install"]
  dir: 'frontend'
- name: node:16.13.0
  entrypoint: npm
  args: ["run", "build"]
  dir: 'frontend'
  env:
  - 'CI = false'
- name: "gcr.io/cloud-builders/gcloud"
  args: ["app", "deploy"]
timeout: "1600s"