# cloudbuild.yaml
steps:
- name: node
  entrypoint: npm
  args: ["install"]
- name: node
  entrypoint: npm
  args: ["run", "build"]
  env:
  - 'CI = false'
- name: "gcr.io/cloud-builders/gcloud"
  args: ["app", "deploy"]
timeout: "1600s"